env:
  global:
    - secure: csNTxydihJNzSV0vr5ECyrbDJuV9bUW5hhK0xzBb/HSGs/Ty5f27ymEAEeYeaCPoprk4juyWE2GlrbKqbIjagDy8njBNs+3BUzLQFVcZ5rr+mXzfZv8vzIYLke6Yor4aApFdk9YVUL4Y2IL+Go0q9UCzjA8MuYB/fdvL2EwvkwGh5/VRsfFi+cmxEAeif1433V3Ilw92CZSaTgKl2nqj5IK13jmdvz2Nh/OMdhZVxL3To8qP02RKkVtj3aDgXGFQyluivYkkGYTqoYT3qua6feaQBVXR1Ogkk1KikYjtx4Ar/u6PGHZSCzQeAoSmBEy7JLIMMeBK5uD/nrBxWam4+jHRQUziB7CzC0lLUYZkPDHF2MuZyaS2tuZWc8a/P6UJO+OrPUYe5jT5RhMuVxXY4as9qdfvFxa2XNbNOblBvPcAm0H3Wp1WIxlM/JXF/cIoLhZXfiapEorIPm+9QJGfvNfmVf6tYKknnxcMEdl1gPeQR8a7+SCZYkGyGcfSqgpGMofEgklAXcBvT7WxNiSh8NbTve/VdHtfEjPFxPuiTPG6/OzuQDv6qVd5Zg9OArhpRAB6v0n7gNsQuHZXWpV4VQRbi/TenL7Fd+ZhzzwKvz/Ni0/sXThwmTgTRlWIFqehklJqK4xaZO0lA288PsL5fvVu0kZinw/bLrSjUSCM7X8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.2o7Net_git_FadeMind
    - GIT_BRANCH: master
    - UPDATE_ME_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/update_me.py
    - ADMIN_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/admin.py

dist: xenial
sudo: required

language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install dead-hosts-launcher

script:
  - dead_hosts_launcher

notifications:
  email:
    recipients:
      - dead-hosts@funilrys.com
    on_success: never
    on_failure: always
